CREATE TABLE TB_ITEMS_ORDER (
    id SERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    price DECIMAL(19, 2) NOT NULL,

    FOREIGN KEY (order_id) REFERENCES TB_ORDER(id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES TB_ITEMS(id)
);